# Generated by Django 3.2.9 on 2021-11-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0003_creator_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Creator',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
